apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/ --volumes hostPath
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: modeling
  name: modeling
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: modeling
    spec:
      containers:
      - env:
        - name: MLFLOW_TRACKING_URI
          value: http://tracker-workflow2:8002
        image: modeling
        imagePullPolicy: IfNotPresent
        name: modeling-20200117213243
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: modeling-hostpath0
        - mountPath: /mlflow
          name: modeling-hostpath1
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/guess/Desktop/scanflow/examples/demo1/data-science/ad-stuff/ad-meta/compose-kubernetes/home/guess/Desktop/scanflow/examples/demo1/data-science
        name: modeling-hostpath0
      - hostPath:
          path: /home/guess/Desktop/scanflow/examples/demo1/data-science/ad-stuff/ad-meta/compose-kubernetes/home/guess/Desktop/scanflow/examples/demo1/data-science/ad-stuff/ad-tracker/tracker-workflow2
        name: modeling-hostpath1
status: {}
