apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/ --volumes hostPath
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: tracker-workflow2
  name: tracker-workflow2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tracker-workflow2
    spec:
      containers:
      - image: tracker-workflow2
        imagePullPolicy: IfNotPresent
        name: tracker-workflow2-20200117213243
        ports:
        - containerPort: 8002
        resources: {}
        volumeMounts:
        - mountPath: /mlflow
          name: tracker-workflow2-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/guess/Desktop/scanflow/examples/demo1/data-science/ad-stuff/ad-meta/compose-kubernetes/home/guess/Desktop/scanflow/examples/demo1/data-science/ad-stuff/ad-tracker/tracker-workflow2
        name: tracker-workflow2-hostpath0
status: {}
