apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o configs/ --volumes hostPath
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: tracker-workflow2
  name: tracker-workflow2
spec:
  ports:
  - name: "8007"
    port: 8007
    targetPort: 8002
  selector:
    io.kompose.service: tracker-workflow2
status:
  loadBalancer: {}
