# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

basic:
  image_tag_version: "latest"
  scanflow_controller_image_name: "172.30.0.49:5000/scanflow-controller"
  scanflow_artifacts_image_name: "172.30.0.49:5000/scanflow-artifacts"
  image_pull_policy: "IfNotPresent"