version: '3'
services:
  requester:
    image: requester
    container_name: requester-20210223161828
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo2/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/demo2/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    tty: 'true'
  tracker-workflow1:
    image: tracker-workflow1
    container_name: tracker-workflow1-20210223161828
    networks:
    - network-workflow1
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo2/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    ports:
    - 8006:8001
networks:
  network_workflow1: null
