version: '3'
services:
  predictor:
    image: predictor
    container_name: predictor-20210322133206
    networks:
    - network-mnist
    depends_on:
    - tracker-mnist
    environment:
      MLFLOW_TRACKING_URI: http://tracker-mnist:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/demo_mnist/data-science/ad-stuff/ad-tracker/tracker-mnist:/mlflow
    tty: 'true'
  tracker-mnist:
    image: tracker-mnist
    container_name: tracker-mnist-20210322133206
    networks:
    - network-mnist
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/data-science/ad-stuff/ad-tracker/tracker-mnist:/mlflow
    ports:
    - 8007:8002
networks:
  network_mnist: null
