import os

def get_scanflow_paths(app_dir):
    # 1. save workflow defined by user
    workflow_dir = os.path.join(app_dir, 'workflow')
    # 2. start template agent inside, and user modify the agents
    agents_dir = os.path.join(app_dir, 'agents')
    tracker_dir = os.path.join(agents_dir, 'tracker')
    checker_dir = os.path.join(agents_dir, 'checker')
    improver_dir = os.path.join(agents_dir, 'improver')
    planner_dir = os.path.join(agents_dir, 'planner')
    # 3. meta data generated by scanflow(for example, workflow.json) 
    meta_dir = os.path.join(app_dir, 'meta')
    deploy_dir = os.path.join(meta_dir, 'deploy')#maybe generate app

    paths = {'app_dir': app_dir,
                'workflow_dir': workflow_dir,
                'agents_dir': agents_dir,
                'meta_dir': meta_dir,
                'tracker_dir': tracker_dir,
                'checker_dir': checker_dir,
                'improver_dir': improver_dir,
                'planner_dir': planner_dir,
                'deploy': deploy_dir}

    return paths